src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, src/k8s-extension/setup.py
=> add customization for microsoft.azureml.kubernetes

src/k8s-extension/azext_k8s_extension/_validators.py, src/k8s-extension/azext_k8s_extension/custom.py
=> Fix Private build of k8s-extension

src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, src/k8s-extension/setup.py
=> change amlk8s to amlarc

k8s-custom-pipelines.yml, src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/azext_metadata.json, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
=> Servicebus client model changes

testing/Cleanup.ps1, testing/test/extensions/public/AzureDefender.Tests.ps1, testing/test/extensions/public/AzureMLKubernetes.Tests.ps1, testing/test/extensions/public/AzureMonitor.Tests.ps1, testing/test/extensions/public/OpenServiceMesh.Tests.ps1, testing/test/helper/Helper.ps1
=> Update tests to only check extensionconfig creation

src/k8s-extension/azext_k8s_extension/vendored_sdks/models/_models.py, src/k8s-extension/azext_k8s_extension/vendored_sdks/models/_models_py3.py
=> Fix Identity Being in Wrong Location in Model

src/k8s-extension/azext_k8s_extension/custom.py
=> Ignore Identity Create for Appliances

src/k8s-configuration/azext_k8s_configuration/_params.py
=> Fix Default Help Text for Parameters

testing/test/extensions/public/OpenServiceMesh.Tests.ps1
=> Update OSM Version to be a Valid Version

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
Remove private preview warning for inference in microsoft.azureml.kubernetes.
=> remove inference private review warning message

src/k8s-extension/azext_k8s_extension/tests/latest/recordings/test_k8s_extension.yaml, src/k8s-extension/azext_k8s_extension/tests/latest/test_k8s_extension_scenario.py
=> Update Unit Testing from OSM to Dapr

src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py
Signed-off-by: Sanya Kochhar <kochhars@microsoft.com>
---
=> osm: enable system identities

src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py, src/k8s-extension/azext_k8s_extension/tests/latest/test_open_service_mesh.py
Signed-off-by: nshankar13 <nshankar@microsoft.com>
---
=> Change extension validation logic osm-arc

src/k8s-configuration/azext_k8s_configuration/action.py
=> Use KustomizationPatch instead of Kustomization for internal rep

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
=> fix install issue on aks

src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/vendored_sdks/v2022_03_01/models/_models_py3.py
=> Provide no default values for Patch of Extension

src/k8s-extension/azext_k8s_extension/_params.py, src/k8s-extension/azext_k8s_extension/custom.py
=> Fix warning message returned on PATCH

testing/pipeline/k8s-custom-pipelines.yml
=> Only test k8s-configuration in Integration Testing

src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py
Signed-off-by: nshankar13 <nshankar@microsoft.com>
---
=> Fix osm-arc installation non-connected clusters

.github/CODEOWNERS
=> change codeowners for k8s extension & configuration

.github/CODEOWNERS
=> modify codeowners for k8s-configuration

testing/pipeline/k8s-custom-pipelines.yml
=> CI fix[k8s-configuration]: deprecate python version 3.6 use in testing

testing/pipeline/k8s-custom-pipelines.yml, testing/test/extensions/public/Flux.Tests.ps1
pr description: This pr only includes addition of test cases for flux extension that will be added in CI test pipeline.
---
=> add test case for flux extension

testing/pipeline/k8s-custom-pipelines.yml, testing/pipeline/templates/run-test.yml
=> change to supportable platform version to fix the test case failures

src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
---
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.
=> [k8s-extension] ContainerInsights Extension Managed Identity Auth Enabled by default

src/aks-preview/azext_aks_preview/tests/latest/data/datacollectionsettings.json, src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
---
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.
=> [k8s-extension] add kind tag in DCR creation
