src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
=> legal warning added

src/k8s-extension/HISTORY.rst, src/k8s-extension/HISTORY_private.rst, src/k8s-extension/azext_k8s_extension/_client_factory.py, src/k8s-extension/azext_k8s_extension/_validators.py, src/k8s-extension/azext_k8s_extension/consts.py, src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, src/k8s-extension/setup.py, src/k8s-extension/setup_private.py, testing/test/extensions/public/AzureMLKubernetes.Tests.ps1
=> Merge in k8s-extension/public (0.3.1)

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, testing/test/extensions/public/AzureMLKubernetes.Tests.ps1
=> Fixed scoring fe related extension param names

src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureDefender.py, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, src/k8s-extension/azext_k8s_extension/partner_extensions/Cassandra.py, src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py, src/k8s-extension/azext_k8s_extension/partner_extensions/DefaultExtension.py, src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py, src/k8s-extension/azext_k8s_extension/partner_extensions/PartnerExtensionModel.py, src/k8s-extension/azext_k8s_extension/tests/latest/recordings/test_k8s_extension.yaml, src/k8s-extension/azext_k8s_extension/tests/latest/test_k8s_extension_scenario.py, src/k8s-extension/azext_k8s_extension/tests/latest/test_open_service_mesh.py
=> Add Custom Delete Logic for Partners

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
=> Add warning message when deleting amlarc extension

src/k8s-extension/HISTORY.rst, src/k8s-extension/azext_k8s_extension/consts.py, src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/vendored_sdks/models/_models.py, src/k8s-extension/azext_k8s_extension/vendored_sdks/models/_models_py3.py, src/k8s-extension/setup.py, testing/test/extensions/public/AzureMonitor.Tests.ps1, testing/test/helper/Helper.ps1
=> Don't Send Identity Headers If In DF

src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py
This PR removes the version check for the Open Service Mesh part of the extension. By passing in no version, we can allow the platform to choose the latest version in the specified release train.
This also removes the check for auto upgrade minor version. Again, it is best to allow the platform to determine if auto upgrade should be set if not explicitly passed in. The platform will do the following:
- Set auto upgrade to true if there is no version specified (defaulting to latest for the release train)
- Set auto upgrade to false if there is a specified version
The …
=> Remove OSM version requirement and auto upgrade check

src/k8s-configuration/azext_k8s_configuration/_help.py, src/k8s-configuration/azext_k8s_configuration/custom.py
- This upgrade in chart version will provide support for the next agent version with `apiextensions/v1`
---
=> Upgrade Helm Operator Chart Version Default

src/k8s-extension/azext_k8s_extension/consts.py, src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/tests/latest/MockClasses.py, src/k8s-extension/azext_k8s_extension/tests/latest/test_custom.py, src/k8s-extension/azext_k8s_extension/tests/latest/test_open_service_mesh.py
=> Fix DF Check for Creating Extension Identity

src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py
=> Add dapr extension

src/k8s-configuration/HISTORY.rst, src/k8s-configuration/azext_k8s_configuration/_help.py, src/k8s-configuration/azext_k8s_configuration/_params.py, src/k8s-configuration/azext_k8s_configuration/commands.py, src/k8s-configuration/azext_k8s_configuration/consts.py, src/k8s-configuration/azext_k8s_configuration/custom.py, src/k8s-configuration/azext_k8s_configuration/format.py, src/k8s-configuration/azext_k8s_configuration/providers/FluxConfigurationProvider.py, testing/pipeline/templates/run-test.yml
=> Add a Deployed Object List to the Flux CLI

src/k8s-configuration/azext_k8s_configuration/format.py
=> Update Formatting for Deployed Object

src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, src/k8s-extension/azext_k8s_extension/partner_extensions/DefaultExtension.py, src/k8s-extension/azext_k8s_extension/partner_extensions/PartnerExtensionModel.py
---
- [yes ] Have you run `python scripts/ci/test_index.py -q` locally?
=> Add one more prompt for amlarc extension update

testing/test/configurations/Flux.Bucket.Tests.ps1, testing/test/configurations/Flux.CrossKind.Tests.ps1
=> Bucket Testing for E2E Testing

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
=> support sslSecret

src/k8s-configuration/HISTORY.rst, src/k8s-configuration/azext_k8s_configuration/_help.py, src/k8s-configuration/azext_k8s_configuration/_params.py, src/k8s-configuration/azext_k8s_configuration/consts.py, src/k8s-configuration/azext_k8s_configuration/providers/FluxConfigurationProvider.py, src/k8s-configuration/setup.py, testing/test/configurations/Flux.Bucket.Tests.ps1, testing/test/configurations/Flux.CrossKind.Tests.ps1
=> Fix Help Text and Parameters for Bucket Scenarios

testing/pipeline/k8s-custom-pipelines.yml, testing/pipeline/templates/build-extension.yml, testing/pipeline/templates/run-test.yml
=> Build Extension in Template

src/k8s-extension/azext_k8s_extension/custom.py, src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py, src/k8s-extension/azext_k8s_extension/utils.py
=> Fix k8s-extension/private Build Issues

src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
---
Bring back ContainerInsights solution in MSI mode
=> [k8s-extension] Bring back containerInsights solution addition in msi mode

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py
=> Use cluster scale to control clusterPurpose and inferenceRouterHA

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureDefender.py
=> k8s-extension azuredefender namespace to mdc

testing/pipeline/k8s-custom-pipelines.yml, testing/pipeline/templates/build-extension.yml
Fix for CI failure issues: [Issue description(pr link)](https://github.com/Azure/azure-cli-extensions/pull/5218)
---
=> CI fix: deprecate python version 3.6 use in testing

src/k8s-extension/azext_k8s_extension/custom.py
=>  Create identity for appliances

src/k8s-extension/azext_k8s_extension/_client_factory.py
=> adding the api version to the operation definition in the client factory

src/k8s-extension/HISTORY.rst, src/k8s-extension/setup.py
=> bump k8s-extension version to 1.3.6

scripts/ci/source_code_static_analysis.py
Disable PyLint for now, as the new version has breaking changes and requires lot more fixes
---
=> Disable PyLint

src/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py
---
This PR updates the version comparison logic in Dapr extension. Earlier, it was using a string comparison, this PR upgrades it to use semver using `packaging.version`.
=> [Dapr] Update version comparison logic to use semver based comparison

src/aks-preview/azext_aks_preview/tests/latest/data/datacollectionsettings.json, src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py
---
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.
=> ContainerInsights extension - Extend dataCollectionSettings with containerlogv2

src/k8s-extension/azext_k8s_extension/partner_extensions/Dapr.py
---
`packaging.version` had some short comings, viz. it can parse currently supported Dapr versions but not the ones that we will introduce in future. This can be fixed by using the `semver` package. azure-cli already depends on semver==2.13.0 https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/setup.py which we can leverage (similar to the fleet extension).
This PR uses semver to parse versions and compare them (to check for downgrades).
You only need to update …
=> [Dapr] Use `semver` instead of `packaging`

src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMonitorMetrics.py, src/k8s-extension/azext_k8s_extension/partner_extensions/ContainerInsights.py, src/k8s-extension/azext_k8s_extension/utils.py
This PR will introduce a new 'virtual' configuration setting named `skipPrerequisites` for Azure Monitor K8s extensions. When it's set as `true`, CLI will skip provisioning/deprovisioning of prerequisites considering the below scenarios:
- Advanced users want to create those prerequisites and fill in the related configuration settings by themselves.
- For some cloud, some ARM resource types in prerequisites are not support.
---
You only need to update the version …
=> Add support to skip provisioning of prerequisites for Azure Monitor K8s extensions

src/k8s-extension/azext_k8s_extension/partner_extensions/OpenServiceMesh.py
---
Currently, after the update to Python3.9, the versioning check as part of the OSM-Arc distro validations will fail and block installation for OSM-Arc test image tags that are used as part of our CI/CD pipelines. To unblock the OSM-Arc CI/CD workflow and release process, this change is needed to only perform the semver check for prod OSM-Arc charts. 
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in …
=> Fix osm-arc version check for CI tags
